---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Event Server"
host: "localhost:8080"
basePath: "/"
produces:
- "application/json"
paths:
  /aggregate:
    get:
      tags:
      - "aggregate"
      operationId: "getAggregate"
      parameters:
      - name: "aggregateId"
        in: "query"
        description: "The aggregateId of the aggregate root which the events belong\
          \ to"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/aggregateBody"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/errorResponse"
      x-swagger-router-controller: "Aggregate"
  /event:
    get:
      tags:
      - "event"
      operationId: "getEvent"
      parameters:
      - name: "aggregateId"
        in: "query"
        description: "The aggregateId of the aggregate root which the events belong\
          \ to"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/eventBody"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/errorResponse"
      x-swagger-router-controller: "Event"
  /commit:
    post:
      tags:
      - "commit"
      operationId: "commit"
      description: 'Commit aggregate and event data'
      parameters:
        - name: commitAggregate
          required: true
          in: body
          schema:
            $ref: "#/definitions/commitAggregateBody"
      responses:
        200:
          description: "Success"
          schema:
            title: Return String
            type: string
            example: Aggregates Added
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/errorResponse"
      x-swagger-router-controller: "Commit"
definitions:
  commitAggregateBody:
    type: "object"
    properties:
      commitAggregateItems:
        type: "array"
        items:
          $ref: "#/definitions/commitAggregate"
  commitAggregate:
    type: object
    properties:
      aggregate:
        $ref: "#/definitions/aggregate"
      eventItems:
        type: "array"
        items:
          $ref: "#/definitions/event"
  aggregateBody:
    type: "object"
    $ref: "#/definitions/aggregateItems"
  aggregateItems:
    type: "array"
    items:
      $ref: "#/definitions/aggregate"
  aggregate:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
  eventBody:
    type: "object"
    $ref: "#/definitions/eventItems"
  eventItems:
    type: array
    items:
      $ref: "#/definitions/event"
  event:
    type: "object"
    properties:
      id:
        type: "string"
      type:
        type: "string"
      version:
        type: "integer"
        format: "int32"
      aggregate:
        $ref: "#/definitions/aggregate"
  errorResponse:
    required:
    - "message"
    properties:
      message:
        type: "string"
